<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="GemBox.Document" Version="2026.8.113" />
    <PackageVersion Include="GemBox.Pdf" Version="2026.8.107" />
    <PackageVersion Include="GemBox.Presentation" Version="2026.8.107" />
    <PackageVersion Include="GemBox.Spreadsheet" Version="2026.8.108" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="NUnit" Version="4.6.1" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageVersion Include="ProjectDefaults" Version="1.0.176" />
    <PackageVersion Include="Verify" Version="31.28.0" />
    <PackageVersion Include="Verify.DiffPlex" Version="3.3.1" />
    <PackageVersion Include="Verify.ImageMagick" Version="3.10.0" />
    <PackageVersion Include="Verify.NUnit" Version="31.28.0" />
  </ItemGroup>
</Project>